apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | b64enc }}
  API_KEY: {{ .Values.secret.apiKey | b64enc }}